### ISSUE TITLE
Auto-fit Column in tFileExcelSheetOutput incompatible with tFileExcelWorkbookOpen memory saving mode

### ISSUE THREAD

**Issue by GotoLink** [jlolling/talendcomp_tFileExcel#15]
Basic setup:
tFileExcelWorkbookOpen (memory saving checked)
tFixedFlowInput (schema with one column) > tFileExcelSheetOutput (everything default except autofit column in schema)
tFileExcelWorkbookSave

Crash report:
Exception in component tFileExcelSheetOutput_1 (Test)
java.lang.IllegalStateException: Could not auto-size column. Make sure the column was tracked prior to auto-sizing the column.
	at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1546)
	at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1500)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.setupColumnSize(SpreadsheetOutput.java:507)
	at datamodel.test_0_1.Test.tFixedFlowInput_1Process(Test.java:1237)
	at datamodel.test_0_1.Test.tFileExcelWorkbookOpen_1Process(Test.java:450)
	at datamodel.test_0_1.Test.runJobInTOS(Test.java:1643)
	at datamodel.test_0_1.Test.main(Test.java:1492)
Caused by: java.lang.IllegalStateException: Cannot get best fit column width on untracked column 0. Either explicitly track the column or track all columns.
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.getBestFitColumnWidth(AutoSizeColumnTracker.java:278)
	at org.apache.poi.xssf.streaming.SXSSFSheet.autoSizeColumn(SXSSFSheet.java:1543)
[statistics] disconnected
	... 6 more
Caused by: java.lang.IllegalStateException: Column was never explicitly tracked and isAllColumnsTracked() is false (trackAllColumns() was never called or untrackAllColumns() was called after trackAllColumns() was called).
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.getBestFitColumnWidth(AutoSizeColumnTracker.java:275)
	... 7 more

That was unexpected since that isn't explained in tFileExcelSheetOutput doc.

**Comment by jlolling** [comment]
This is not a bug, it is a limitation of the streaming mode. The streaming mode keeps only a small portion of the xml structure of the excel file within the memory and concatenate them at the end to the final document. This allows to write very huge excel documents but has the limitation not all necessary parts of the excel document are available to the job code at the end.
I will update the component documentation.
