### ISSUE TITLE
Reference to depreciated method?

### ISSUE THREAD

**Issue by TMaddern** [jlolling/talendcomp_tFileExcel#3]
Hi Jlolling,

I've been using your packages for a while and firstly wish to say THANK YOU for these.
I'm having trouble either with dependencies or there is a possible reference to a depreciated method, I'm just not technical enough to work out which, or what.

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(Lorg/apache/poi/ss/usermodel/Workbook;)I
	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:78)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:624)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:645)
	at org.talend.ExcelTool.prepareXlsxFile(ExcelTool.java:131)
	at ...`

Any help you might render would be appreciated .

**Comment by jlolling** [comment]
The problem here is the very out dated Apache POI version used in Talend.
Do not mix both kind of excel components within one job.

**Comment by TMaddern** [comment]
Thank you Jan!
