### ISSUE TITLE
Strict OOXML isn't currently supported

### ISSUE THREAD

**Issue by Anatoli87** [jlolling/talendcomp_tFileExcel#33]
With the latest version of library (13.5) i cannot open files written with open version (Strict open xml)

```
Exception in component tFileExcelWorkbookOpen_1 (Test_workbook)
org.apache.poi.ooxml.POIXMLException: Strict OOXML isn't currently supported, please see bug #57699
	at org.apache.poi.ooxml.POIXMLDocumentPart.getPartFromOPCPackage(POIXMLDocumentPart.java:779)
	at org.apache.poi.ooxml.POIXMLDocumentPart.<init>(POIXMLDocumentPart.java:175)
	at org.apache.poi.ooxml.POIXMLDocumentPart.<init>(POIXMLDocumentPart.java:165)
	at org.apache.poi.ooxml.POIXMLDocument.<init>(POIXMLDocument.java:61)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:282)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
```

Previously by 13.2 it has worked perfect.

Used talend version: R2021-11-7.3.1

Could you please help?

**Comment by jlolling** [comment]
I am a little bit surprised you mean it has worked in previous versions.
The problem is caused by the underlaying Apache POI library.
Actually I have seen this message regarding this issue:
However, Apache POI only supports real Excel workbooks and not Strict Open XML Spreadsheets. This is in the pipeline for Apache but isn't planned yet.
I will update the components to the very latest release and check if it works.

**Comment by jlolling** [comment]
Here is the current discussion of the Apache developers: https://bz.apache.org/bugzilla/show_bug.cgi?id=57699
I thing the current best way is to build a small component function to convert the document if needed. I will take a look at it. I am currently on vacation. I will start working on it starting in September - not earlier unfortunately.
