### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by Tostino** [jlolling/talendcomp_tFileExcel#36]
Hi there, I was just wanting to check with you and see what version compatibility there is with your components vs Talend Open Studio (DI)?

I ask, because I am using your 13.5 release along with TOS_DI-20200219_1130-V7.3.1, and I also have some regular Talend excel components within a job, and there seems to be incompatibility between them on export due to classloading issues.

![image](https://user-images.githubusercontent.com/8227578/206558712-18a8d359-7f99-4119-916f-ddc7e22bc3b1.png)
which caused 
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.apache.poi.ooxml.util.DocumentHelper
        at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:431)
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:520)
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1505)
        at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:460)
        at org.apache.poi.ooxml.POIXMLDocument.close(POIXMLDocument.java:204)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.close(XSSFWorkbook.java:594)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.close(SXSSFWorkbook.java:935)
        at org.talend.ExcelTool.writeExcel(ExcelTool.java:377)
        at gosimple_etl.manufacturer_inboundfeed_subjob_export_load_results_0_1.manufacturer_inboundfeed_subjob_export_load_results.tPostgresqlInput_1Process(manufacturer_inboundfeed_subjob_export_load_results.java:5007)
        at gosimple_etl.manufacturer_inboundfeed_subjob_export_load_results_0_1.manufacturer_inboundfeed_subjob_export_load_results.tPostgresqlRow_3Process(manufacturer_inboundfeed_subjob_export_load_results.java:3890)
        at
.....
```

**Comment by jlolling** [comment]
If you use the custom component, actually there is no use case which is covered from the build-in components which is not covered by the custom components. I obviously recommend using the custom component.

**Comment by jlolling** [comment]
Actually I have sticked with the 4-version of Apache POI because of trying to keep it compatible. Apache POI is actually on version 5 an I am planning to update to this new major version because of some serious enhancements regarding memory consumption.

**Comment by Tostino** [comment]
Yeah, I understand. I believe the reasoning for putting the job together like it was, is due to the speed issues using your components in specific instances (also requires huge heap). Those cases where it caused issues we replaced with the built in Talend components for a huge speed-up when we didn't need the more advanced features of your components.

And in my case, this was done in a job hierarchy that had 8 different subjobs, and one of them had been modified to have that built-in excel component for speed reasons.

Would you maybe put a warning in the readme about this incompatibility? I didn't see anything about it when looking, because I figured it was the issue.

**Comment by jlolling** [comment]
Did you have tried the Memory Saving Mode in the options of the tFileExcelWorkbookOpen?
This is designed to significant reduce the memory usage and save therefore a lot of CPU usage.
It use internally the SFFX workbook from Apache POI.

**Comment by Tostino** [comment]
Yeah, we had tried just about everything with the configuration of this library before we swapped those out.

Either way, would just be a good idea to mention in the README.md and the Talend Exchange listing that this is incompatible with the standard talend components: [list of components] and to not use them in the same job/subjob in the dependency graph.

Thanks for answering.
