### ISSUE TITLE
Streaming workbook does not work while append data

### ISSUE THREAD

**Issue by jlolling** [jlolling/talendcomp_tFileExcel#38]
The tFileExcelSheetOutput component rise an exception when appending data in streaming mode.
java.lang.IllegalArgumentException: Attempting to write a row[4] in the range [0,1003] that is already written to disk.
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:146)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:45)
	at de.jlo.talendcomp.excel.SpreadsheetFile.getRow(SpreadsheetFile.java:542)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.writeRow(SpreadsheetOutput.java:187)

**Comment by jlolling** [comment]
First result. The patched class SXSSFSheet is not used anymore, instead the class shipped with Apache POI 5.2.3

**Comment by jlolling** [comment]
The patched SXSSFSheet works well. The append mode works now also in Streaming mode.
Will publish the solution as version 13.8
