### ISSUE TITLE
NoSuchMethodException when using tFileExcelSheetOutput in jobflow

### ISSUE THREAD

**Issue by simonrutter** [jlolling/talendcomp_tFileExcel#6]
Good morning jlolling,

First of all, many thanks for taking time to build all these excellent custom components for Talend; you have no idea how much time you have saved me overall.

I'm running into a slightly unusual issue when trying to run a job featuring these components in Talend Studio for Cloud 6.3.1:

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Cell.setCellType(Lorg/apache/poi/ss/usermodel/CellType;)V
	at de.jlo.talendcomp.excel.SpreadsheetOutput.writeCellValue(SpreadsheetOutput.java:430)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.writeRow(SpreadsheetOutput.java:214)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tLoop_2Process(DynamicSchemaTest.java:2293)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tFileInputFullRow_1Process(DynamicSchemaTest.java:1708)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tFileInputDelimited_1Process(DynamicSchemaTest.java:1252)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tJava_1Process(DynamicSchemaTest.java:729)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tFileExcelWorkbookOpen_1Process(DynamicSchemaTest.java:597)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.tLibraryLoad_1Process(DynamicSchemaTest.java:2732)
	at talendadgexcloud.dynamicschematest_0_1.DynamicSchemaTest.runJobInTOS(DynamicSchemaTest.java:3843)

I did a bit of looking into this error earlier and many of the posts I've found online state that this error could be related to the version of POI.jar used in the components. I tried loading the most recent release of POI (3.17), but that hasn't helped. 

Would you kindly be able to point me in the right direction of what may be wrong? I'd love to be able to use these components as, yet again, they would allow me to achieve the optimal output for the jobs I've got in question. 

Many thanks in advance and I hope you have an excellent day ahead of you.

All the best,

Simon

**Comment by jlolling** [comment]
Hi Simon,

the most common reason for such issues is you have mixed Talend build-in components (e.g. tFileOutputExcel) in your job with my components. Talend uses usually mostly out-dated libraries and these libs will be loaded first.
My components uses the most recent libraries and their classes cannot be loaded of such a class is already loaded formally.

Advise: Please deactivate other most likely excel related components and check when the error disappears.

Best regards
Jan Lolling

**Comment by simonrutter** [comment]
Good morning Jan,

Many thanks for your response. The job in question does not contain any tFileExcel components and following your instructions, I made an extremely simple job to test out if any of the simpler components I had in there could have been the cause. 
Unfortunately, I am still receiving the same error. I have also tried manually importing the POI-3.17.jar file but this has not helped either. One thing I noticed during my testing of this was that if I set the Spreadsheet type to XLSX with Memory saving enabled, I get the following error instead: 

Exception in thread "main" java.lang.NoSuchFieldError: RETURN_NULL_AND_BLANK
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:213)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:239)
	at de.jlo.talendcomp.excel.SpreadsheetFile.initializeWorkbook(SpreadsheetFile.java:447)
	at talendadgexcloud.dynamicschematest2_0_1.DynamicSchemaTest2.tFileExcelWorkbookOpen_1Process(DynamicSchemaTest2.java:435)
at talendadgexcloud.dynamicschematest2_0_1.DynamicSchemaTest2.runJobInTOS(DynamicSchemaTest2.java:2620)
	at talendadgexcloud.dynamicschematest2_0_1.DynamicSchemaTest2.main(DynamicSchemaTest2.java:2454)

As you can see, it's slightly different. Not sure if this will help you in any way, but it can't hurt to have more data. In case it will somehow help; I will attach the job to this message. I don't believe I have the components incorrectly organised. 

Many thanks again for your patience in helping me with this. It is hugely appreciated. 

Have an amazing day.

Simon

[DynamicSchemaTest2.zip](https://github.com/jlolling/talendcomp_tFileExcel/files/1559032/DynamicSchemaTest2.zip)

**Comment by simonrutter** [comment]
Good afternoon Jan,

I hope you are doing well and that you had a lovely weekend.

I am pleased to report that after switching to a different version of Talend, the issues that were occurring before have now alleviated themselves. I'm thrilled at all the new possibilities that this opens up for us!

Many thanks again for making these components and I hope you have a fantastic evening and a very Merry Christmas! Feel free to mark this issue as resolved now.

All the best,

Simon
